baseURL = "http://yesmynameisbilly.github.io"
title = "Billy v0.48"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Billy McChristian"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Billy McChristian's personal website"
keywords = "blog,developer,personal"
info = ["Linux Systems Engineer / DevOps Engineer", "Aspiring Developer"]
avatarURL = "images/avatar.jpg"
#gravatar = ""
dateFormat = "January 2, 2006"
since = ""
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/yesmynameisbilly"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-lg fa-github"
weight = 1
url = "https://github.com/yesmynameisbilly/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-lg fa-gitlab"
weight = 2
url = "https://gitlab.com/yesmynameisbilly"

# [[params.social]]
# name = "Twitter"
# icon = "fa fa-2x fa-twitter"
# weight = 3
# url = "https://twitter.com/johndoe/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-lg fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/billymcchristian/"

# [[params.social]]
# name = "Medium"
# icon = "fa fa-2x fa-medium"
# weight = 5
# url = "https://medium.com/@johndoe"

[[params.social]]
name = "Email"
icon = "fa fa-lg fa-envelope"
weight = 6
url = "mailto:billy.mcchristian@gmail.com"
# rel = "alternate"
# type = "application/rss+xml"

# [languages.en]
# languageName = ":us:"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "Resume / CV"
weight = 3
url = "resume/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"


# [languages.pt-br]
# languageName = ":brazil:"
# title = "João Ninguém"

# [languages.pt-br.params]
# author = "João Ninguém"
# info = "Full Stack DevOps e Mágico"
# description = "Sítio pessoal de João Ninguém"
# keywords = "blog,desenvolvedor,pessoal"

# [[languages.pt-br.menu.main]]
# name = "Sobre"
# weight = 1
# url = "about/"

# [[languages.pt-br.menu.main]]
# name = "Blog"
# weight = 2
# url = "posts/"

# [[languages.pt-br.menu.main]]
# name = "Projetos"
# weight = 3
# url = "projects/"

# [[languages.pt-br.menu.main]]
# name = "Contato"
# weight = 5
# url = "contact/"
